### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by sealldeveloper** [brumik/ollama-obsidian-indexer#10]
I am on a Mac M1 and tried the following steps you included, including configuring the `.env` and the program exits with `Illegal instruction: 4` when running `python index.py`.

**Comment by brumik** [comment]
Sorry, I am unable to try this out on MacM1.

**Comment by sealldeveloper** [comment]
> Sorry, I am unable to try this out on MacM1.

Is there any troubleshooting/debug methods I could do to provide you with more information?

**Comment by brumik** [comment]
I never seen illegal instructions, but I think what happening is that some of the libs used are not compatible with your architecture. You could try to remove any cache and pip requirements file as well as downloaded packages. Then you can try to run the index.py which will throw missing package errors. You then just can always install the missing package. This will take a while, but there is a higher chance that if the package was fixed upstream or there is an M1 version of it you will get it.

**Comment by brumik** [comment]
@sealldeveloper I think the lates update may fix your issue as well: https://github.com/brumik/ollama-obsidian-indexer/issues/6#issuecomment-2119252573

**Comment by brumik** [comment]
This is not reproducible and I expect outdated.
