### ISSUE TITLE
Remove requirement for indexer to have access to vault files

### ISSUE THREAD

**Issue by CalebFenton** [brumik/ollama-obsidian-indexer#3]
First, cool project! I forked and made some changes to support talking to remote ollama instances and create a dockerfile, but hit a major problem. It looks like the indexing API only takes a file path and relies on having access to the vault files. It should be easy to pass the text (and the path) to remove this limitation.

My motivation is that I do not intend to run an instance of this indexing on every machine I use Obsidian on. I want to run a single container to manage indexing and have all my obsidian instances point to that. Text files are pretty small, so this increase in data sent should be fine. It should be pretty easy to enable compression on the indexer if large text files are a concern.

What do you think?

**Comment by CalebFenton** [comment]
Or you could just steal what I've done already: https://github.com/brumik/ollama-obsidian-indexer/compare/main...CalebFenton:ollama-obsidian-indexer:main

I haven't tested the docker stuff because of the problem I mentioned above.

**Comment by brumik** [comment]
I feel you but maybe you could host it on your server where you also have access to the obsidian vault? 

I was thinking of sending the whole file but that poses the problem of keeping the indexes in sync. Now it does indexing of the whole dir (cached) when you start obsidian with this plugin, then on any change to a file. The change could be kinda feasible as long as we just want to index text, but even then the startup check could be problematic on big vaults.

Also startup check is needed as you can modify the files in your vault countless other ways or without having the extension enabled. It can happen that if you delete something sensible from your vault that we would keep it in the index, potentially creating unpleasant moments at best. 

In the future I would also like to incorporate PDF and maybe image indexing or other file formats optionally which would also need high bandwith.

Though we can already tell the app where to find the vault as long as they have access to the filesystem here: https://github.com/brumik/ollama-obsidian-indexer/blob/main/.env.sample#L16 (I have it mounted as samba service for example to my pc with a graphics card.

**Comment by brumik** [comment]
Also thank you for the contribution, I will try to see if I can build on it further!

**Comment by CalebFenton** [comment]
Ah I see why it's not easy to just send the whole file. Thanks for explaining!

I may need to work on another approach entirely. My containers run on a headless linux server, and all my obsidian vaults are synced using self hosted live sync.

Just thinking "out loud" here, not suggesting how this project should change. May be able to use checksums to avoid re-indexing at startup.

When Obsidian starts,
* For each file, calculate the checksum and map to file path
* Send the vault name + batch of checksums
* Indexing server checks if there are any new or missing checksums
* If the indexer had a checksum for that vault that wasn't sent with the vault name + checksum batch, remove it from the vault. If it's not in any vault, delete the index. Report this checksum as removed from vault. (may be useful for debugging)
* If there are any new checksums the indexer doesn't have, tell the plugin
* Plugin checks if any new checksums requested by indexer and sends file contents

I have no clue how obsidian plugins work or what their limitations are. Not sure how viable this is.

**Comment by brumik** [comment]
Yeah, no problem, currently we do avoid re indexing by keeping the internal document store, but on change I would need to send it anyways. The checksum mechanism could be cool, but the communication is one sided from obsidian plugin so for not I'd like to avoid implementing a 2 way communication. 

Though you made me interested in your live sync setup, could you share how you did it? I had it trough samba and synology drive for mobile, but it is not perfect.

**Comment by brumik** [comment]
cc @McCrory since your solution could work together with this one (just in case you are interested). I will try to marry the two solutions.

**Comment by CalebFenton** [comment]
@brumik https://github.com/vrtmrz/obsidian-livesync It's a plugin you install. It takes a little configuring and you hahve to run couchdb. Here's  my docker-compose.yml:

```yaml
version: '3'

services:
  couchdb:
    image: couchdb
    environment:
      COUCHDB_USER: AzureDiamond
      COUCHDB_PASSWORD: hunter2
    volumes:
      - ./data/local.ini:/opt/couchdb/etc/local.ini
    ports:
      - "5984:5984"
    restart: always
```

And in case it wasn't clear, I'm not suggesting "real" bidirectional two-way communication, just typical REST API behavior of:
* client sends something
* server responds with more than a 200 status code, e.g. a json object
* do something based on that response
