### ISSUE TITLE
Ollama on external machine

### ISSUE THREAD

**Issue by KeithIMyers** [brumik/ollama-obsidian-indexer#8]
Good Morning,
The laptop I currently use for Obsidian lacks a decent GPU so I offload Ollama to a different machine and access it over a VPN. Is there any way to set this up so it connects to 10.0.0.XX instead of 127.0.0.1

**Comment by brumik** [comment]
Hello, I forgot to merge my update branch (because docker do not work on it) but I will do it today:

#4 (this has a variable for the URL, which should be what you looking for.

**Comment by brumik** [comment]
#4 Merged, now you should be able to set in your env file the URL for your ollama. Let me knows if it works
